### PR TITLE
Contubuters section

### PR DESCRIPTION
**Pull request by Emberzo**
This pull request includes significant updates to the project, including new features for fetching and displaying contributor data, enhancements to the layout and styling of the site, and improvements to the configuration. The most important changes are summarized below:

### New Features:
* Added a new component `Contributors` to fetch and display active and inactive contributors using the GitHub GraphQL API. This includes handling missing tokens, processing data, and updating the DOM with contributor information. (`src/components/Contubuters.astro`, `src/pages/about.astro`) [[1]](diffhunk://#diff-dc89edd077156da246579181e0cc137c767b94e0e970eed2db08369063a5a6a4R1-R399) [[2]](diffhunk://#diff-cb33463363c150558e340277672bb5c583640ddb38012f53a33ed69125d92038R5) [[3]](diffhunk://#diff-cb33463363c150558e340277672bb5c583640ddb38012f53a33ed69125d92038R36)

### Layout and Styling Enhancements:
* Updated the `Header` component to include a new class for styling and improved the layout with additional elements such as a logo, navigation items, and theme toggle. (`src/components/Header.astro`, `src/layouts/Layout.astro`) [[1]](diffhunk://#diff-cef92c86af879f90a7ac8087da782381ed31160251d9960fe59f7ee29389a9beL12-R12) [[2]](diffhunk://#diff-ba00f1d7bc63648f0861e03d786d6f1ed78307f1b40284e4db329586d3df2db2R1-R180)
* Added a new style block to the `Hero` component to enhance its visual appearance, including responsive design adjustments. (`src/components/Hero.astro`)

### CODE REVIEW

**Comment by Emberzo** [comment]
for this to deploy I need to add the api key to the GitHub secrets we also need to update the deploy script to see the api key

**Comment by Emberzo** [comment]
something like this for the deploy.yml


```yml

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install, build, and upload
        uses: withastro/action@v1
        with:
          path: ./
          node-version: 18
          package-manager: npm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```

**Comment by hsmith-dev** [comment]
Let me know when GITHUB_TOKEN is changed to CONTRIBUTOR_SECRET
Thanks

**Comment by Emberzo** [comment]
the deploy.yml is done and everything should be working on commit now

**Pull request merged**
